# Pratice Session 1

using [world-happiness-report-2021.csv](../resources/world-happiness-report-2021.csv) for solving 30 questions ranging from easy, medium and hard

🟢 Easy (1–10)
🟡 Medium (11–20)
🔴 Hard (21–30)

In [39]:
import pandas as pd

1. Load the dataset into a DataFrame.

In [40]:
df = pd.read_csv("../resources/world-happiness-report-2021.csv")

2. Display the first 10 rows of the dataset.

In [41]:
print(df.head(10))

  Country name     Regional indicator  Ladder score  \
0      Finland         Western Europe         7.842
1      Denmark         Western Europe         7.620
2  Switzerland         Western Europe         7.571
3      Iceland         Western Europe         7.554
4  Netherlands         Western Europe         7.464
5       Norway         Western Europe         7.392
6       Sweden         Western Europe         7.363
7   Luxembourg         Western Europe         7.324
8  New Zealand  North America and ANZ         7.277
9      Austria         Western Europe         7.268

   Standard error of ladder score  upperwhisker  lowerwhisker  \
0                           0.032         7.904         7.780
1                           0.035         7.687         7.552
2                           0.036         7.643         7.500
3                           0.059         7.670         7.438
4                           0.027         7.518         7.410
5                           0.035         7.462         7.323
6                           0.036         7.433         7.293
7                           0.037         7.396         7.252
8                           0.040         7.355         7.198
9                           0.036         7.337         7.198

   Logged GDP per capita  Social support  Healthy life expectancy  \
0                 10.775           0.954                     72.0
1                 10.933           0.954                     72.7
2                 11.117           0.942                     74.4
3                 10.878           0.983                     73.0
4                 10.932           0.942                     72.4
5                 11.053           0.954                     73.3
6                 10.867           0.934                     72.7
7                 11.647           0.908                     72.6
8                 10.643           0.948                     73.4
9                 10.906           0.934                     73.3

   Freedom to make life choices  Generosity  Perceptions of corruption  \
0                         0.949      -0.098                      0.186
1                         0.946       0.030                      0.179
2                         0.919       0.025                      0.292
3                         0.955       0.160                      0.673
4                         0.913       0.175                      0.338
5                         0.960       0.093                      0.270
6                         0.945       0.086                      0.237
7                         0.907      -0.034                      0.386
8                         0.929       0.134                      0.242
9                         0.908       0.042                      0.481

   Ladder score in Dystopia  Explained by: Log GDP per capita  \
0                      2.43                             1.446
1                      2.43                             1.502
2                      2.43                             1.566
3                      2.43                             1.482
4                      2.43                             1.501
5                      2.43                             1.543
6                      2.43                             1.478
7                      2.43                             1.751
8                      2.43                             1.400
9                      2.43                             1.492

   Explained by: Social support  Explained by: Healthy life expectancy  \
0                         1.106                                  0.741
1                         1.108                                  0.763
2                         1.079                                  0.816
3                         1.172                                  0.772
4                         1.079                                  0.753
5                         1.108                                  0.782
6                         1.062                                  0.763
7                         1.003                                  0.760
8                         1.094                                  0.785
9                         1.062                                  0.782

   Explained by: Freedom to make life choices  Explained by: Generosity  \
0                                       0.691                     0.124
1                                       0.686                     0.208
2                                       0.653                     0.204
3                                       0.698                     0.293
4                                       0.647                     0.302
5                                       0.703                     0.249
6                                       0.685                     0.244
7                                       0.639                     0.166
8                                       0.665                     0.276
9                                       0.640                     0.215

   Explained by: Perceptions of corruption  Dystopia + residual
0                                    0.481                3.253
1                                    0.485                2.868
2                                    0.413                2.839
3                                    0.170                2.967
4                                    0.384                2.798
5                                    0.427                2.580
6                                    0.448                2.683
7                                    0.353                2.653
8                                    0.445                2.612
9                                    0.292                2.784

3. Find the number of rows and columns.

In [42]:
dimensions = df.shape

print(f"Dataset Dimensions:\nRows: {dimensions[0]}\nColumns: {dimensions[1]}")

Dataset Dimensions:
Rows: 149
Columns: 20

4. List all column names.

In [43]:
print("Columns:\n")

for i, column in enumerate(df.columns):
    print(f"{i+1}: {column}")

Columns:

1: Country name
2: Regional indicator
3: Ladder score
4: Standard error of ladder score
5: upperwhisker
6: lowerwhisker
7: Logged GDP per capita
8: Social support
9: Healthy life expectancy
10: Freedom to make life choices
11: Generosity
12: Perceptions of corruption
13: Ladder score in Dystopia
14: Explained by: Log GDP per capita
15: Explained by: Social support
16: Explained by: Healthy life expectancy
17: Explained by: Freedom to make life choices
18: Explained by: Generosity
19: Explained by: Perceptions of corruption
20: Dystopia + residual

5. Check the data type of each column.

In [44]:
print(df.dtypes)

Country name                                   object
Regional indicator                             object
Ladder score                                  float64
Standard error of ladder score                float64
upperwhisker                                  float64
lowerwhisker                                  float64
Logged GDP per capita                         float64
Social support                                float64
Healthy life expectancy                       float64
Freedom to make life choices                  float64
Generosity                                    float64
Perceptions of corruption                     float64
Ladder score in Dystopia                      float64
Explained by: Log GDP per capita              float64
Explained by: Social support                  float64
Explained by: Healthy life expectancy         float64
Explained by: Freedom to make life choices    float64
Explained by: Generosity                      float64
Explained by: Perceptions of corruption       float64
Dystopia + residual                           float64
dtype: object

6. Identify columns that contain missing values.

In [45]:
missing_columns = df.columns[df.isnull().sum() > 0]
print(missing_columns)

Index([], dtype='object')

7. Count the total number of missing values in the dataset.

In [46]:
print(df.isnull().sum().sum())

0

8. Display summary statistics for all numerical columns.

In [47]:
df.describe()

,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.00,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000,149.000000
mean,5.532839,0.058752,5.648007,5.417631,9.432208,0.814745,64.992799,0.791597,-0.015134,0.727450,2.43,0.977161,0.793315,0.520161,0.498711,0.178047,0.135141,2.430329
std,1.073924,0.022001,1.054330,1.094879,1.158601,0.114889,6.762043,0.113332,0.150657,0.179226,0.00,0.404740,0.258871,0.213019,0.137888,0.098270,0.114361,0.537645
min,2.523000,0.026000,2.596000,2.449000,6.635000,0.463000,48.478000,0.382000,-0.288000,0.082000,2.43,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.648000
25%,4.852000,0.043000,4.991000,4.706000,8.541000,0.750000,59.802000,0.718000,-0.126000,0.667000,2.43,0.666000,0.647000,0.357000,0.409000,0.105000,0.060000,2.138000
50%,5.534000,0.054000,5.625000,5.413000,9.569000,0.832000,66.603000,0.804000,-0.036000,0.781000,2.43,1.025000,0.832000,0.571000,0.514000,0.164000,0.101000,2.509000
75%,6.255000,0.070000,6.344000,6.128000,10.421000,0.905000,69.600000,0.877000,0.079000,0.845000,2.43,1.323000,0.996000,0.665000,0.603000,0.239000,0.174000,2.794000
max,7.842000,0.173000,7.904000,7.780000,11.647000,0.983000,76.953000,0.970000,0.542000,0.939000,2.43,1.751000,1.172000,0.897000,0.716000,0.541000,0.547000,3.482000

9. Find the average happiness score across all countries.

In [48]:
df["Ladder score"].mean()

np.float64(5.532838926174497)

10. Find the country with the highest happiness score.

In [49]:
df.sort_values(by="Ladder score", ascending=False).head(1)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.78,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253

11. Find the country with the lowest happiness score.

In [50]:
df.sort_values(by="Ladder score").head(1)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.37,0.0,0.126,0.0,0.122,0.01,1.895

12. List the top 10 happiest countries.

In [51]:
df.sort_values(by="Ladder score", ascending=False).head(10)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
5,Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.3,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
6,Sweden,Western Europe,7.363,0.036,7.433,7.293,10.867,0.934,72.7,0.945,0.086,0.237,2.43,1.478,1.062,0.763,0.685,0.244,0.448,2.683
7,Luxembourg,Western Europe,7.324,0.037,7.396,7.252,11.647,0.908,72.6,0.907,-0.034,0.386,2.43,1.751,1.003,0.760,0.639,0.166,0.353,2.653
8,New Zealand,North America and ANZ,7.277,0.040,7.355,7.198,10.643,0.948,73.4,0.929,0.134,0.242,2.43,1.400,1.094,0.785,0.665,0.276,0.445,2.612
9,Austria,Western Europe,7.268,0.036,7.337,7.198,10.906,0.934,73.3,0.908,0.042,0.481,2.43,1.492,1.062,0.782,0.640,0.215,0.292,2.784

13. List the bottom 10 least happy countries.

In [52]:
df.sort_values(by="Ladder score").head(10)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
143,Malawi,Sub-Saharan Africa,3.600,0.092,3.781,3.419,6.958,0.537,57.948,0.780,0.038,0.729,2.43,0.113,0.168,0.298,0.484,0.213,0.134,2.190
142,Haiti,Latin America and Caribbean,3.615,0.173,3.953,3.276,7.477,0.540,55.700,0.593,0.422,0.721,2.43,0.294,0.173,0.227,0.257,0.463,0.139,2.060
141,Tanzania,Sub-Saharan Africa,3.623,0.071,3.762,3.485,7.876,0.702,57.999,0.833,0.183,0.577,2.43,0.433,0.540,0.300,0.549,0.307,0.231,1.263
140,Yemen,Middle East and North Africa,3.658,0.070,3.794,3.521,7.578,0.832,57.122,0.602,-0.147,0.800,2.43,0.329,0.831,0.272,0.268,0.092,0.089,1.776
139,Burundi,Sub-Saharan Africa,3.775,0.107,3.985,3.565,6.635,0.490,53.400,0.626,-0.024,0.607,2.43,0.000,0.062,0.155,0.298,0.172,0.212,2.876

14. Find the average happiness score by region.

In [53]:
df.groupby(["Regional indicator"])["Ladder score"].mean()

Regional indicator
Central and Eastern Europe            5.984765
Commonwealth of Independent States    5.467000
East Asia                             5.810333
Latin America and Caribbean           5.908050
Middle East and North Africa          5.219765
North America and ANZ                 7.128500
South Asia                            4.441857
Southeast Asia                        5.407556
Sub-Saharan Africa                    4.494472
Western Europe                        6.914905
Name: Ladder score, dtype: float64

15. Find which region has the highest average happiness score.

In [54]:
df.groupby(["Regional indicator"])["Ladder score"].mean().sort_values(ascending=False).head(1)

Regional indicator
North America and ANZ    7.1285
Name: Ladder score, dtype: float64

16. Find how many countries belong to each region.

In [55]:
df.groupby(["Regional indicator"]).size()

Regional indicator
Central and Eastern Europe            17
Commonwealth of Independent States    12
East Asia                              6
Latin America and Caribbean           20
Middle East and North Africa          17
North America and ANZ                  4
South Asia                             7
Southeast Asia                         9
Sub-Saharan Africa                    36
Western Europe                        21
dtype: int64

17. Find the range (max − min) of happiness scores for each region.

In [56]:
df.groupby(["Regional indicator"])["Ladder score"].agg(["min", "max"])

                                      min    max
Regional indicator
Central and Eastern Europe          5.101  6.965
Commonwealth of Independent States  4.875  6.179
East Asia                           5.339  6.584
Latin America and Caribbean         3.615  7.069
Middle East and North Africa        3.658  7.157
North America and ANZ               6.951  7.277
South Asia                          2.523  5.269
Southeast Asia                      4.426  6.377
Sub-Saharan Africa                  3.145  6.049
Western Europe                      5.536  7.842

18. Find countries whose happiness score is above the global average.

In [57]:
global_average_happiness_score = df["Ladder score"].mean()

df[df["Ladder score"] > global_average_happiness_score]["Country name"]

0                Finland
1                Denmark
2            Switzerland
3                Iceland
4            Netherlands
             ...
70              Paraguay
71            Montenegro
72    Dominican Republic
73          North Cyprus
74               Belarus
Name: Country name, Length: 75, dtype: object

19. Sort countries by GDP per capita and list the top 10.

In [58]:
df.sort_values("Logged GDP per capita", ascending=False).head(10)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
7,Luxembourg,Western Europe,7.324,0.037,7.396,7.252,11.647,0.908,72.600,0.907,-0.034,0.386,2.43,1.751,1.003,0.760,0.639,0.166,0.353,2.653
31,Singapore,Southeast Asia,6.377,0.043,6.460,6.293,11.488,0.915,76.953,0.927,-0.018,0.082,2.43,1.695,1.019,0.897,0.664,0.176,0.547,1.379
14,Ireland,Western Europe,7.085,0.040,7.164,7.006,11.342,0.947,72.400,0.879,0.077,0.363,2.43,1.644,1.092,0.753,0.606,0.238,0.367,2.384
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
24,United Arab Emirates,Middle East and North Africa,6.561,0.039,6.637,6.484,11.085,0.844,67.333,0.932,0.074,0.589,2.43,1.555,0.860,0.594,0.670,0.236,0.223,2.422
5,Norway,Western Europe,7.392,0.035,7.462,7.323,11.053,0.954,73.300,0.960,0.093,0.270,2.43,1.543,1.108,0.782,0.703,0.249,0.427,2.580
18,United States,North America and ANZ,6.951,0.049,7.047,6.856,11.023,0.920,68.200,0.837,0.098,0.698,2.43,1.533,1.030,0.621,0.554,0.252,0.154,2.807
76,Hong Kong S.A.R. of China,East Asia,5.477,0.049,5.573,5.380,11.000,0.836,76.820,0.717,0.067,0.403,2.43,1.525,0.841,0.893,0.408,0.232,0.342,1.236
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

20. Find the average life expectancy for countries with happiness score above 6.

In [59]:
df[df["Ladder score"] > 6]["Healthy life expectancy"].mean().round()

np.float64(70.0)